spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
server.port=5052

spring.datasource.username=YonMbl
spring.datasource.password=Pass1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

